// <auto-generated />
using System;
using KomunalniProblemi.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KomunalniProblemi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.Dokument", b =>
                {
                    b.Property<int>("DokumentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DokumentID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PrijavaID")
                        .HasColumnType("int");

                    b.Property<string>("Tip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DokumentID");

                    b.HasIndex("PrijavaID");

                    b.ToTable("Dokumenti");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.KomunalnaSluzba", b =>
                {
                    b.Property<int>("SluzbaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SluzbaID"));

                    b.Property<string>("Kontakt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SluzbaID");

                    b.ToTable("KomunalneSluzbe");

                    b.HasData(
                        new
                        {
                            SluzbaID = 1,
                            Kontakt = "inspekcija@komunalno.cacak.rs",
                            Naziv = "Komunalna inspekcija"
                        },
                        new
                        {
                            SluzbaID = 2,
                            Kontakt = "rasveta@komunalno.cacak.rs",
                            Naziv = "Javna rasveta"
                        });
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.KomunalniProblem", b =>
                {
                    b.Property<int>("ProblemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProblemID"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProblemID");

                    b.ToTable("KomunalniProblemi");

                    b.HasData(
                        new
                        {
                            ProblemID = 1,
                            Naziv = "Rupa na putu",
                            Opis = "Oštećenje puta"
                        },
                        new
                        {
                            ProblemID = 2,
                            Naziv = "Javna rasveta",
                            Opis = "Neispravna/ugašena rasveta"
                        },
                        new
                        {
                            ProblemID = 3,
                            Naziv = "Otpad",
                            Opis = "Divlja deponija / neodneto smeće"
                        });
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.Korisnik", b =>
                {
                    b.Property<int>("KorisnikID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KorisnikID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prezime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KorisnikID");

                    b.ToTable("Korisnici");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.Lokacija", b =>
                {
                    b.Property<int>("LokacijaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LokacijaID"));

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Opis")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LokacijaID");

                    b.ToTable("Lokacije");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.Prijava", b =>
                {
                    b.Property<int>("PrijavaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PrijavaID"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KorisnikID")
                        .HasColumnType("int");

                    b.Property<int>("LokacijaID")
                        .HasColumnType("int");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProblemID")
                        .HasColumnType("int");

                    b.Property<int?>("SluzbaID")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("PrijavaID");

                    b.HasIndex("KorisnikID");

                    b.HasIndex("LokacijaID");

                    b.HasIndex("ProblemID");

                    b.HasIndex("SluzbaID");

                    b.ToTable("Prijave");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.Dokument", b =>
                {
                    b.HasOne("KomunalniProblemi.Domain.Entities.Prijava", "Prijava")
                        .WithMany("Dokumenti")
                        .HasForeignKey("PrijavaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Prijava");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.Prijava", b =>
                {
                    b.HasOne("KomunalniProblemi.Domain.Entities.Korisnik", "Korisnik")
                        .WithMany("Prijave")
                        .HasForeignKey("KorisnikID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomunalniProblemi.Domain.Entities.Lokacija", "Lokacija")
                        .WithMany("Prijave")
                        .HasForeignKey("LokacijaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomunalniProblemi.Domain.Entities.KomunalniProblem", "KomunalniProblem")
                        .WithMany("Prijave")
                        .HasForeignKey("ProblemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KomunalniProblemi.Domain.Entities.KomunalnaSluzba", "KomunalnaSluzba")
                        .WithMany("Prijave")
                        .HasForeignKey("SluzbaID");

                    b.Navigation("KomunalnaSluzba");

                    b.Navigation("KomunalniProblem");

                    b.Navigation("Korisnik");

                    b.Navigation("Lokacija");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.KomunalnaSluzba", b =>
                {
                    b.Navigation("Prijave");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.KomunalniProblem", b =>
                {
                    b.Navigation("Prijave");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.Korisnik", b =>
                {
                    b.Navigation("Prijave");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.Lokacija", b =>
                {
                    b.Navigation("Prijave");
                });

            modelBuilder.Entity("KomunalniProblemi.Domain.Entities.Prijava", b =>
                {
                    b.Navigation("Dokumenti");
                });
#pragma warning restore 612, 618
        }
    }
}
