@KomunalniProblemi_Api_HostAddress = http://localhost:5166

### Health
GET {{KomunalniProblemi_Api_HostAddress}}/health

### POST - kreiranje prijave
POST {{KomunalniProblemi_Api_HostAddress}}/api/prijave
Content-Type: application/json

{
  "korisnikID": 1,
  "problemID": 1,
  "lokacijaID": 1,
  "sluzbaID": 1,
  "opis": "Rupa ispred zgrade, velika i opasna."
}

### GET - lista prijava
GET {{KomunalniProblemi_Api_HostAddress}}/api/prijave